"""init

Revision ID: 59923a7e05d3
Revises: 
Create Date: 2023-04-11 14:18:01.243334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59923a7e05d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_project_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=True),
    sa.Column('tc_id', sa.String(length=50), server_default='', nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='unique_project_id_name')
    )
    op.create_index(op.f('ix_tbl_project_role_project_id'), 'tbl_project_role', ['project_id'], unique=False)
    op.create_index(op.f('ix_tbl_project_role_tc_id'), 'tbl_project_role', ['tc_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_name', table_name='student')
    op.drop_index('idx_no', table_name='student')
    op.drop_table('student')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('no', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_no', 'student', ['no'], unique=False)
    op.create_index('idx_name', 'student', ['name'], unique=False)
    op.drop_table('user')
    op.drop_index(op.f('ix_tbl_project_role_tc_id'), table_name='tbl_project_role')
    op.drop_index(op.f('ix_tbl_project_role_project_id'), table_name='tbl_project_role')
    op.drop_table('tbl_project_role')
    # ### end Alembic commands ###
